sonarqube-check:
  image: gradle:jre11-slim
  stage: build
  script: 
    - |
      echo Performing sonar scan in $SONAR_HOST_URL 
      gradle sonarqube -Dsonar.qualitygate.wait=true -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=$SONAR_HOST_URL
  allow_failure: true
  only:
    - merge_requests
    - master
